const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const {createRequire}=require('node:module');
const root=process.cwd(),baseline='C:/Users/Lan/AppData/Local/Temp/sanmou-cr-baseline-20260908';
const appReq=createRequire(path.join(root,'apps/sanmou-advisor-desktop/package.json'));
const ts=appReq('typescript'),React=appReq('react'),ssr=appReq('react-dom/server');
function parsed(file){const text=fs.readFileSync(file,'utf8');return ts.createSourceFile(file,text,ts.ScriptTarget.Latest,true,file.endsWith('tsx')?ts.ScriptKind.TSX:ts.ScriptKind.TS);}
function compile(text){return ts.transpileModule(text,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;}
function functionText(file,name,nested=false){let sf=parsed(file),nodes=sf.statements;if(nested)nodes=nodes.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='App').body.statements;const node=nodes.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text===name);return node?node.getText(sf):'';}
function probe(root,old){const file=path.join(root,'apps/sanmou-advisor-desktop/src/electron',old?'main.ts':'python.ts');const ctx={exports:{},spawnSync:require('node:child_process').spawnSync};vm.createContext(ctx);vm.runInContext(compile(functionText(file,'probePython'))+';globalThis.fn=probePython;',ctx);try{return ctx.fn({command:'C:/nonexistent-review-python-77217.exe',args:[],label:'missing'},process.env,root);}catch(e){return {error:e.name};}}
async function race(root){const file=path.join(root,'apps/sanmou-advisor-desktop/src/renderer/App.tsx');const code=['beginSelection','setSelectedFile','onAnalyze'].map(n=>functionText(file,n,true)).join('\n');let resolve;const ctx={exports:{},file:{name:'A.png'},options:{},previewUrl:'blob:A.png',report:null,messages:[],selectionVersion:{current:0},chatVersion:{current:0},URL:{createObjectURL:f=>'blob:'+f.name},crypto:require('node:crypto'),revokePreviewUrl:()=>{},buildReportMessage:()=>'synthetic',refreshHistory:()=>{},analyzeScreenshot:f=>new Promise(r=>resolve=()=>r({name:f.name}))};for(const [setter,key] of Object.entries({setFile:'file',setPreviewUrl:'previewUrl',setReport:'report',setBusy:'busy',setHistoryBusy:'historyBusy',setChatBusy:'chatBusy',setChatInput:'chatInput',setError:'error',setMessages:'messages',setActiveReportTab:'activeTab'}))ctx[setter]=v=>{ctx[key]=typeof v==='function'?v(ctx[key]):v;};vm.createContext(ctx);vm.runInContext(compile(code)+';globalThis.fns={onAnalyze,setSelectedFile};',ctx);const pending=ctx.fns.onAnalyze();ctx.fns.setSelectedFile({name:'B.png'});resolve();await pending;return {selected:ctx.file.name,preview:ctx.previewUrl,report:ctx.report?.name??null};}
function quality(root,unknown){const source=fs.readFileSync(path.join(root,'apps/sanmou-advisor-desktop/src/renderer/App.tsx'),'utf8');const module={exports:{}};const ctx={module,exports:module.exports,require:name=>name==='./api'?{}:appReq(name)};vm.createContext(ctx);vm.runInContext(compile(source)+';exports.Q=EvidenceQualityPanel;',ctx);const evidence={evidence_id:'synthetic',source_type:'vision',ref:'vision.domain:resource_bar',summary:'synthetic',confidence:unknown?0:1,metadata:unknown?{status:'unknown'}:{trusted_for_state:true}};const report={structured_evidence:[evidence],evidence:['synthetic'],confidence:unknown?0:1};const recommended=unknown?null:{execution_blocked_reason:'advisor_mode',confidence:1,structured_evidence:[]};const html=ssr.renderToStaticMarkup(React.createElement(module.exports.Q,{report,recommended}));return {sufficient:html.includes('证据充分'),insufficient:html.includes('证据不足')};}
(async()=>{const result={R03:{baseline:probe(baseline,true),combined:probe(root,false)},R22:{baseline:await race(baseline),combined:await race(root)},R23:{baseline_good:quality(baseline,false),combined_good:quality(root,false),baseline_unknown:quality(baseline,true),combined_unknown:quality(root,true)}};assert.equal(result.R03.baseline.error,'TypeError');assert.equal(result.R03.combined.ok,false);assert.equal(result.R22.baseline.report,'A.png');assert.equal(result.R22.combined.report,null);assert(result.R23.baseline_good.insufficient&&result.R23.combined_good.sufficient&&result.R23.baseline_unknown.sufficient&&result.R23.combined_unknown.insufficient);console.log(JSON.stringify(result,null,2));})().catch(e=>{console.error(e);process.exitCode=1});
