factions:
  魏国: 魏
  蜀国: 蜀
  吴国: 吴
  群雄: 群
troop_types:
  骑兵: 骑兵
  枪兵: 枪兵
  弓兵: 弓兵
  盾兵: 盾兵
  器械: 器械
role_tags:
  输出: 输出
  控制: 控制
  辅助: 辅助
  前排: 前锋
  前锋: 前锋
  中军: 中军
  后排: 后军
  后军: 后军
skill_types:
  主动战法: 主动
  被动战法: 被动
  指挥战法: 指挥
  追击战法: 追击
trigger_types:
  主动战法: 主动
  被动战法: 被动
  指挥战法: 指挥
  追击战法: 追击
target_scopes:
  自身: 自身
  友军单体: 友军单体
  敌军单体: 敌军单体
  友军群体: 友军群体
  敌军群体: 敌军群体
  全体: 全体
rarities:
  橙: 橙
  紫: 紫
  金: 橙

