canonical_map:
  诸葛孔明: 诸葛亮
  卧龙: 诸葛亮
  云长: 关羽
  祝融: 祝融夫人
  甄姬: 甄洛
  SP诸葛亮: 诸葛亮2
  sp诸葛亮: 诸葛亮2
aliases:
  诸葛亮: [诸葛孔明, 卧龙]
  关羽: [云长]
  刘备: [玄德]
  赵云: [子龙]
  祝融夫人: [祝融]
  甄洛: [甄姬]
  诸葛亮2: [SP诸葛亮, sp诸葛亮]
