canonical_map:
  盛气临敌: 盛气凌敌
  横征: 横征暴敛
  清风: 清风驱疾
  束手: 束手无策
  奇门: 奇门遁甲
  王佐: 王佐之才
  谈笑: 谈笑诛心
  折冲: 折冲御侮
  断敌: 断敌粮道
  骁勇: 骁勇之姿
aliases:
  盛气凌敌: [盛气临敌]
  草船借箭: [草船]
  横扫千军: [横扫]
  横征暴敛: [横征]
  清风驱疾: [清风]
  束手无策: [束手]
  奇门遁甲: [奇门]
  王佐之才: [王佐]
  谈笑诛心: [谈笑]
  折冲御侮: [折冲]
  断敌粮道: [断敌]
  骁勇之姿: [骁勇]
